spring:
  datasource:
    url: jdbc:postgresql://db:5432/mydatabase
    username: dev
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
